=== edave64/doki-doki-dialog-generator-pack-format/src/v2/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/edave64/doki-doki-dialog-generator-pack-format/master/src/v1/schema.json",
	"definitions": {
		"folder": {
			"type": "string",
			"title": "The folder, in which all other paths in this file will be searched",
			"default": "/",
			"examples": ["./"],
			"pattern": "^(.*)$"
		}
	},
	"type": "object",
	"title": "The Root Schema",
	"required": ["$schema"],
	"additionalProperties": false,
	"properties": {
		"version": {
			"type": "string",
			"const": "2.0"
		},
		"$schema": {
			"type": "string"
		},
		"packId": {
			"type": "string",
			"title": "The content pack id",
			"pattern": "^(.*)$"
		},
		"packCredits": {
			"type": "string",
			"title": "The credits of the content pack",
			"default": "",
			"examples": [
				"<a href='https://www.reddit.com/dq74jr' target='_blank' rel='noopener noreferrer'>Created by</a> anita6artania"
			],
			"pattern": "^(.*)$"
		},
		"folder": { "$ref": "#/definitions/folder" },
		"character": {
			"type": "array",
			"required": ["id"],
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"title": "The character id",
						"description": "This id needs to be unique for every character. If the name collides with an existing character, they will be merged",
						"pattern": "^(.*)$"
					},
					"name": {
						"type": "string",
						"title": "The name of the character",
						"examples": [],
						"pattern": "^(.*)$"
					},
					"chibi": {
						"type": "string",
						"title": "The path to the chibi file",
						"pattern": "^(.*)$"
					},
					"styleComponents": {
						"type": "array",
						"items": {
							"label": { "type": "string" },
							"name": { "type": "string" },
							"variants": {
								"type": "object",
								"patternProperties": {
									".*": {
										"type": "string"
									}
								},
								"additionalProperties": false
							},
							"additionalProperties": false
						}
					},
					"styles": {
						"type": "array",
						"title": "A list of styles",
						"items": {
							"type": "object",
							"title": "A style",
							"required": ["name", "label"],
							"properties": {
								"name": {
									"type": "string",
									"title": "The name of the style. Of an eye type and/or hair type is included, separated by a minus",
									"default": "",
									"examples": [],
									"pattern": "^(.*)$"
								},
								"label": {
									"type": "string",
									"title": "The display name of the style",
									"default": "",
									"examples": [],
									"pattern": "^(.*)$"
								},
								"styleGroup": {
									"type": "string"
								},
								"components": {
									"type": "object",
									"patternProperties": {
										".*": {
											"type": "string"
										}
									},
									"additionalProperties": false
								}
							}
						}
					},
					"heads": {
						"type": "object",
						"title": "The head groups",
						"patternProperties": {
							".*": {
								"title": "Headgroup",
								"oneOf": [
									{
										"type": "array",
										"items": {
											"type": "string"
										}
									},
									{
										"type": "object",
										"additionalProperties": false,
										"required": ["all"],
										"properties": {
											"all": {
												"type": "array",
												"items": {
													"old$ref": "#/definitions/nsfwAbleImg"
												}
											},
											"folder": {
												"type": "string"
											}
										}
									}
								]
							}
						},
						"additionalProperties": false
					},
					"poses": {
						"type": "array",
						"title": "Poses",
						"items": {
							"type": "object",
							"title": "A pose",
							"required": ["name", "style", "compatibleHeads"],
							"properties": {
								"name": {
									"type": "string",
									"title": "The name of a pose. If a content pack includes a pose with the same name as an existing one, the get merged together",
									"default": "",
									"pattern": "^(.*)$"
								},
								"style": {
									"type": "string",
									"title": "The name of a style",
									"default": "",
									"pattern": "^(.*)$"
								},
								"compatibleHeads": {
									"type": "array",
									"title": "A list of compatible head groups",
									"items": {
										"type": "string",
										"title": "A head group",
										"default": "",
										"pattern": "^(.*)$"
									}
								}
							},
							"oneOf": [
								{
									"required": ["left", "right"],
									"properties": {
										"left": {
											"type": "array",
											"title": "The images for the left side of the pose",
											"items": {
												"old$ref": "#/definitions/nsfwAbleImg",
												"default": "",
												"examples": ["1l.png"],
												"pattern": "^(.*)$"
											}
										},
										"right": {
											"type": "array",
											"title": "The images for the right side of the pose",
											"items": {
												"old$ref": "#/definitions/nsfwAbleImg",
												"default": "",
												"examples": ["1r.png"],
												"pattern": "^(.*)$"
											}
										}
									}
								},
								{
									"required": ["variant"],
									"properties": {
										"variant": {
											"type": "array",
											"title": "The images for the pose",
											"items": {
												"old$ref": "#/definitions/nsfwAbleImg",
												"default": "",
												"examples": ["3.png"],
												"pattern": "^(.*)$"
											}
										}
									}
								},
								{
									"required": ["static"],
									"properties": {
										"static": {
											"title": "The image of the pose",
											"type": "string"
										}
									}
								}
							]
						},
						"additionalProperties": false
					}
				},
				"additionalProperties": false
			}
		}
	}
}

=== edave64/doki-doki-dialog-generator-pack-format/src/v2/amy.json
{
	"$schema": "./schema.json",
	"packId": "buildin.amy",
	"packCredits": "",
	"folder": "amy/",
	"character": [
		{
			"id": "ddlc.fan.amy2",
			"name": "Amy",
			"styles": [
				{
					"name": "uniform",
					"label": "Uniform"
				},
				{
					"name": "casual",
					"label": "Casual attire"
				}
			],
			"heads": {
				"straight": [
					"a",
					"b",
					"c",
					"d",
					"e",
					"f",
					"g",
					"h",
					"i",
					"h",
					"k",
					"l",
					"m",
					"n",
					"o",
					"p",
					"q",
					"r",
					"s",
					"t",
					"u",
					"v",
					"w",
					"x",
					"y",
					"z"
				],
				"straight_broken_glases": ["!1", "!2", "!3", "!4", "!5"]
			},
			"poses": [
				{
					"name": "normal",
					"style": "uniform",
					"compatibleHeads": ["straight", "straight_broken_glases"],
					"left": ["1l", "2l", "3l"],
					"right": ["1r", "2r"],
					"headInForeground": true
				},
				{
					"name": "folded_hands_up",
					"style": "uniform",
					"compatibleHeads": ["straight", "straight_broken_glases"],
					"static": "5"
				},
				{
					"name": "folded_hands_down",
					"style": "uniform",
					"compatibleHeads": ["straight", "straight_broken_glases"],
					"static": "6"
				},
				{
					"name": "hands_on_glasses",
					"style": "uniform",
					"compatibleHeads": ["straight"],
					"left": ["4l"],
					"right": ["1r", "2r"]
				},
				{
					"name": "normal-casual",
					"style": "casual",
					"compatibleHeads": ["straight", "straight_broken_glases"],
					"left": ["1bl", "2bl", "3bl"],
					"right": ["1br", "2br"],
					"headInForeground": true
				},
				{
					"name": "folded_hands_up-casual",
					"style": "casual",
					"compatibleHeads": ["straight", "straight_broken_glases"],
					"static": "5b"
				},
				{
					"name": "folded_hands_down-casual",
					"style": "casual",
					"compatibleHeads": ["straight", "straight_broken_glases"],
					"static": "6b"
				},
				{
					"name": "hands_on_glasses-casual",
					"style": "casual",
					"compatibleHeads": ["straight"],
					"left": ["4bl"],
					"right": ["1br", "2br"]
				}
			]
		}
	]
}
